export const ACTION_TYPE = {
	SET_USER: 'SET_USER',
	LOGOUT: 'LOGOUT',
	SET_ACCOUNT_DATA: 'SET_ACCOUNT_DATA',
	OPEN_MODAL: 'OPEN_MODAL',
	CLOSE_MODAL: 'CLOSE_MODAL',
	RESET_ACCOUNT_DATA: 'RESET_ACCOUNT_DATA',
};
