export const ACTION_TYPE = {
	SET_USER: 'SET_USER',
	LOGOUT: 'LOGOUT',
	SET_ACCOUNT_DATA: 'SET_ACCOUNT_DATA',
	SET_ACCOUNTS: 'SET_ACCOUNTS',
	SET_CATEGORIES: 'SET_CATEGORIES',
	OPEN_MODAL: 'OPEN_MODAL',
	CLOSE_MODAL: 'CLOSE_MODAL',
	RESET_ACCOUNT_DATA: 'RESET_ACCOUNT_DATA',
	SET_FILTER_DATE: 'SET_FILTER_DATE',
	REMOVE_FILTER_DATE: 'REMOVE_FILTER_DATE',
};
